export const SUBSCRIBE_TO_CHANNEL = "SUBSCRIBE_TO_CHANNEL";
export const UNSUBSCRIBE_TO_CHANNEL = "UNSUBSCRIBE_TO_CHANNEL";
export const SWITCH_CHANNEL = "SWITCH_CHANNEL";
export const CHANNEL_EVENT = "CHANNEL_EVENT";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
