export const SUBSCRIBE_TO_CHANNEL = "SUBSCRIBE_TO_CHANNEL";
export const UNSUBSCRIBE_TO_CHANNEL = "UNSUBSCRIBE_TO_CHANNEL";
export const SWITCH_CHANNEL = "SWITCH_CHANNEL";
export const CHANNEL_EVENT = "CHANNEL_EVENT";
export const CHAT_EVENT = "CHAT_EVENT";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const NEW_CHANNEL_MESSAGE = "NEW_CHANNEL_MESSAGE";
export const NEW_HELP_MESSAGE = "NEW_HELP_MESSAGE";

export const SET_AGENT_NAME = "SET_AGENT_NAME";
