export const SUBSCRIBE_TO_CHANNEL = "SUBSCRIBE_TO_CHANNEL";
export const UNSUBSCRIBE_TO_CHANNEL = "UNSUBSCRIBE_TO_CHANNEL";
export const LOAD_CHANNEL_MODULE = "LOAD_CHANNEL_MODULE";
export const UNLOAD_CHANNEL_MODULE = "UNLOAD_CHANNEL_MODULE";
export const SUBSCRIBE_TO_FRIENDS = "SUBSCRIBE_TO_FRIENDS";
export const UNSUBSCRIBE_TO_FRIENDS = "UNSUBSCRIBE_TO_FRIENDS";
export const SUBSCRIBE_TO_AUTH = "SUBSCRIBE_TO_AUTH";
export const UNSUBSCRIBE_TO_AUTH = "UNSUBSCRIBE_TO_AUTH";
export const SWITCH_CHANNEL = "SWITCH_CHANNEL";
export const CHANNEL_EVENT = "CHANNEL_EVENT";
export const CHAT_EVENT = "CHAT_EVENT";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const NEW_CHANNEL_MESSAGE = "NEW_CHANNEL_MESSAGE";
export const NEW_HELP_MESSAGE = "NEW_HELP_MESSAGE";
export const NEW_ERROR_MESSAGE = "NEW_ERROR_MESSAGE";
export const NEW_FRIEND_MESSAGE = "NEW_FRIEND_MESSAGE";
export const NEW_SERVER_MESSAGE = "NEW_SERVER_MESSAGE";
export const AGENT_ACTION_MESSAGE = "AGENT_ACTION_MESSAGE";
export const SET_AGENT_NAME = "SET_AGENT_NAME";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTO_LOGIN = "AUTO_LOGIN";
export const SWAP_COMMAND_STATE = "SWAP_COMMAND_STATE";
export const SET_EDITOR_REF = "SET_EDITOR_REF";
export const NEW_CODE_EDITOR_OUTPUT = "NEW_CODE_EDITOR_OUTPUT";
export const NEW_COMMAND = "NEW_COMMAND";
export const HISTORY_UP = "HISTORY_UP";
export const HISTORY_DOWN = "HISTORY_UP";
export const DEMO_MODE_ON = "DEMO_MODE_ON";
export const DEMO_MODE_OFF = "DEMO_MODE_OFF";
export const AGENT_CANCELLED_DEMO = "AGENT_CANCELLED_DEMO";
export const RESET_AGENT_CANCELLED = "RESET_AGENT_CANCELLED";
export const DEMO_CHANGE_NAME = "DEMO_CHANGE_NAME";
export const JSX_MESSAGE = "JSX_MESSAGE";
export const DEMO_CHANNEL_SET = "DEMO_CHANNEL_SET";

export const types = {
  DEMO_CHANNEL_SET,
  JSX_MESSAGE,
  DEMO_CHANGE_NAME,
  DEMO_MODE_ON,
  DEMO_MODE_OFF,
  AGENT_CANCELLED_DEMO,
  RESET_AGENT_CANCELLED,
  HISTORY_UP,
  HISTORY_DOWN,
  NEW_COMMAND,
  SET_EDITOR_REF,
  NEW_CODE_EDITOR_OUTPUT,
  AGENT_ACTION_MESSAGE,
  SUBSCRIBE_TO_CHANNEL,
  UNSUBSCRIBE_TO_CHANNEL,
  LOAD_CHANNEL_MODULE,
  UNLOAD_CHANNEL_MODULE,
  SUBSCRIBE_TO_FRIENDS,
  UNSUBSCRIBE_TO_FRIENDS,
  SUBSCRIBE_TO_AUTH,
  UNSUBSCRIBE_TO_AUTH,
  SWITCH_CHANNEL,
  CHANNEL_EVENT,
  CHAT_EVENT,
  CLEAR_MESSAGES,
  NEW_MESSAGE,
  NEW_CHANNEL_MESSAGE,
  NEW_HELP_MESSAGE,
  NEW_ERROR_MESSAGE,
  NEW_FRIEND_MESSAGE,
  NEW_SERVER_MESSAGE,
  SET_AGENT_NAME,
  LOGOUT,
  AUTO_LOGIN,
  SWAP_COMMAND_STATE,
  LOGIN,
};
